version: "3.9"

services:
  postgres:
    image: postgres:17.4
    container_name: postgres_csmp
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 3s
      interval: 8s
      timeout: 5s
      retries: 4

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_csmp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # app:
  #   image: php:8.4.5-apache
  #   container_name: sdmp
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./app:/var/www/html
  #   depends_on:
  #     - postgres
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html
