networks:
  sdmp-network:
    name: sdmp-network
    driver: bridge

services:
  mariadb:
    image: mariadb:latest
    container_name: sdmp-mariadb
    restart: always
    environment:
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      start_period: 3s
      interval: 8s
      timeout: 5s
      retries: 4
    networks:
      - sdmp-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sdmp-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT:-5050}:80"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./data/phpmyadmin:/sessions
    networks:
      - sdmp-network

  app:
    image: php:8.4.5-apache
    container_name: sdmp
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - DB_HOST=mariadb
      - APP_DEBUG=${APP_DEBUG:-false}
    command: >
      bash -c "apt-get update && 
      docker-php-ext-install pdo pdo_mysql &&
      a2enmod rewrite && 
      apache2-foreground"
    networks:
      - sdmp-network

