version: "3.9"

networks:
  sdmp-network:
    name: sdmp-network
    driver: bridge

services:
  postgres:
    image: postgres:17.4
    container_name: sdmp-db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 3s
      interval: 8s
      timeout: 5s
      retries: 4
    networks:
      - sdmp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: sdmp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - sdmp-network

  app:
    image: php:8.4.5-apache
    container_name: sdmp
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres
    command: >
      bash -c "apt-get update && 
      apt-get install -y libpq-dev && 
      docker-php-ext-install pdo pdo_pgsql pgsql && 
      a2enmod rewrite &&
      a2enmod mpm_prefork &&
      echo 'ServerName sdmp' >> /etc/apache2/apache2.conf &&
      echo '<Directory /var/www/html>' >> /etc/apache2/apache2.conf &&
      echo '    AllowOverride All' >> /etc/apache2/apache2.conf &&
      echo '</Directory>' >> /etc/apache2/apache2.conf &&
      apache2-foreground"
    networks:
      - sdmp-network
